ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DMsimp_s_spin0__COMPLEX'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_114 = ', GC_114
      WRITE(*,2) 'GC_115 = ', GC_115
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_1__1 = ', GC_1__1
      WRITE(*,2) 'GC_2__1 = ', GC_2__1
      WRITE(*,2) 'GC_3__1 = ', GC_3__1
      WRITE(*,2) 'GC_7__1 = ', GC_7__1
      WRITE(*,2) 'GC_8__1 = ', GC_8__1
