ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_ME,MDL_MU,MDL_VDMM,MDL_MC,MDL_MD,MDL_MW
     $ ,MDL_MXC,MDL_MB,MDL_MXD,MDL_MXR,MDL_MY0,MDL_MS,MDL_MZ,MDL_SDMM
     $ ,MDL_MT,MDL_MTA,MDL_MH

      COMMON/MASSES/ MDL_ME,MDL_MU,MDL_VDMM,MDL_MC,MDL_MD,MDL_MW
     $ ,MDL_MXC,MDL_MB,MDL_MXD,MDL_MXR,MDL_MY0,MDL_MS,MDL_MZ,MDL_SDMM
     $ ,MDL_MT,MDL_MTA,MDL_MH


      DOUBLE PRECISION MDL_WZ,MDL_WY0,MDL_WT,MDL_WFDM,MDL_WH,MDL_WSDM
     $ ,MDL_WW,MDL_WVDM

      COMMON/WIDTHS/ MDL_WZ,MDL_WY0,MDL_WT,MDL_WFDM,MDL_WH,MDL_WSDM
     $ ,MDL_WW,MDL_WVDM


      DOUBLE COMPLEX GC_114, GC_115, GC_13, GC_14, GC_1__1, GC_2__1,
     $  GC_3__1, GC_7__1, GC_8__1

      COMMON/COUPLINGS/ GC_114, GC_115, GC_13, GC_14, GC_1__1, GC_2__1
     $ , GC_3__1, GC_7__1, GC_8__1

