ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'mdl_gSXr = ', MDL_GSXR
      WRITE(*,*) 'mdl_gSXc = ', MDL_GSXC
      WRITE(*,*) 'mdl_gSXd = ', MDL_GSXD
      WRITE(*,*) 'mdl_gPXd = ', MDL_GPXD
      WRITE(*,*) 'mdl_gSd11 = ', MDL_GSD11
      WRITE(*,*) 'mdl_gSu11 = ', MDL_GSU11
      WRITE(*,*) 'mdl_gSd22 = ', MDL_GSD22
      WRITE(*,*) 'mdl_gSu22 = ', MDL_GSU22
      WRITE(*,*) 'mdl_gSd33 = ', MDL_GSD33
      WRITE(*,*) 'mdl_gSu33 = ', MDL_GSU33
      WRITE(*,*) 'mdl_gPd11 = ', MDL_GPD11
      WRITE(*,*) 'mdl_gPu11 = ', MDL_GPU11
      WRITE(*,*) 'mdl_gPd22 = ', MDL_GPD22
      WRITE(*,*) 'mdl_gPu22 = ', MDL_GPU22
      WRITE(*,*) 'mdl_gPd33 = ', MDL_GPD33
      WRITE(*,*) 'mdl_gPu33 = ', MDL_GPU33
      WRITE(*,*) 'mdl_Lambda = ', MDL_LAMBDA
      WRITE(*,*) 'mdl_gSg = ', MDL_GSG
      WRITE(*,*) 'mdl_gPg = ', MDL_GPG
      WRITE(*,*) 'mdl_gSh1 = ', MDL_GSH1
      WRITE(*,*) 'mdl_gSh2 = ', MDL_GSH2
      WRITE(*,*) 'mdl_gSb = ', MDL_GSB
      WRITE(*,*) 'mdl_gPb = ', MDL_GPB
      WRITE(*,*) 'mdl_gSw = ', MDL_GSW
      WRITE(*,*) 'mdl_gPw = ', MDL_GPW
      WRITE(*,*) 'mdl_sSIe = ', MDL_SSIE
      WRITE(*,*) 'mdl_fSIe = ', MDL_FSIE
      WRITE(*,*) 'mdl_vSIe = ', MDL_VSIE
      WRITE(*,*) 'mdl_fSDe = ', MDL_FSDE
      WRITE(*,*) 'mdl_vSDe = ', MDL_VSDE
      WRITE(*,*) 'MU_R = ', MU_R
      WRITE(*,*) 'mdl_MD = ', MDL_MD
      WRITE(*,*) 'mdl_MU = ', MDL_MU
      WRITE(*,*) 'mdl_MS = ', MDL_MS
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MXc = ', MDL_MXC
      WRITE(*,*) 'mdl_MXd = ', MDL_MXD
      WRITE(*,*) 'mdl_MY0 = ', MDL_MY0
      WRITE(*,*) 'mdl_MXr = ', MDL_MXR
      WRITE(*,*) 'mdl_sdmm = ', MDL_SDMM
      WRITE(*,*) 'mdl_vdmm = ', MDL_VDMM
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WY0 = ', MDL_WY0
      WRITE(*,*) 'mdl_Wsdm = ', MDL_WSDM
      WRITE(*,*) 'mdl_Wfdm = ', MDL_WFDM
      WRITE(*,*) 'mdl_Wvdm = ', MDL_WVDM
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_GDMS = ', MDL_GDMS
      WRITE(*,*) 'mdl_GDMA = ', MDL_GDMA
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_gPu33__exp__2 = ', MDL_GPU33__EXP__2
      WRITE(*,*) 'mdl_gSu33__exp__2 = ', MDL_GSU33__EXP__2
      WRITE(*,*) 'mdl_sqrt__6 = ', MDL_SQRT__6
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_I2a33 = ', MDL_I2A33
      WRITE(*,*) 'mdl_I3a33 = ', MDL_I3A33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_yt__exp__2 = ', MDL_YT__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_G__exp__4 = ', MDL_G__EXP__4
