C     -----------------------------------------------------------------
C     -------c
      SUBROUTINE GETFSMASSES_ANN(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the annihilation processes.                          
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     



      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      SUBROUTINE GETFSMASSES_DM2DM(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the DM -> DM processes.                              
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     PMASS_MADDM2 --- generates series of if-then-else to read
C      appropriate final state masses



      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      SUBROUTINE GETFSMASSES_SCATTERING(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the DM/SM scattering processes.                      
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     PMASS_MADDM3 --- generates series of if-then-else to read
C      appropriate final state masses



      RETURN
      END




C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_ANN(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an individual       
C            c
C     annihlation process.                                            
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM1 --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_ANN = SMATRIX
      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DM2DM(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an idividual DM ->
C      DM      c
C     process.                                                        
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K


C     SMATRIX_MADDM2 --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_DM2DM = SMATRIX
      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_SCATTERING(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process.                                             
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K


C     SMATRIX_MADDM3 --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_SCATTERING = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process relevant for direct detection.               
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_DD --- generates series of if-then-else statements
C      to call appropriate smatrix
      IF (K.EQ.1) THEN
        CALL XDT_XDT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.2) THEN
        CALL XDXT_XDXT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.3) THEN
        CALL XDTX_XDTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.4) THEN
        CALL XDXTX_XDXTX_SMATRIX(P_EXT, SMATRIX)

      ENDIF

      SMATRIX_DD = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD_EFF(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process in the effective operator framework          
C            c
C     relevant for direct detection.                                  
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_EFF_DD --- generates series of if-then-else
C      statements to call appropriate smatrix
      IF (K.EQ.1) THEN
        CALL EFT_SI_XDT_XDT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.2) THEN
        CALL EFT_SI_XDXT_XDXT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.3) THEN
        CALL EFT_SI_XDTX_XDTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.4) THEN
        CALL EFT_SI_XDXTX_XDXTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.5) THEN
        CALL EFT_SD_XDT_XDT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.6) THEN
        CALL EFT_SD_XDXT_XDXT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.7) THEN
        CALL EFT_SD_XDTX_XDTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.8) THEN
        CALL EFT_SD_XDXTX_XDXTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.9) THEN
        CALL EFT_SI_XDD_XDD_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.10) THEN
        CALL EFT_SI_XDXD_XDXD_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.11) THEN
        CALL EFT_SI_XDDX_XDDX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.12) THEN
        CALL EFT_SI_XDXDX_XDXDX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.13) THEN
        CALL EFT_SD_XDD_XDD_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.14) THEN
        CALL EFT_SD_XDXD_XDXD_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.15) THEN
        CALL EFT_SD_XDDX_XDDX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.16) THEN
        CALL EFT_SD_XDXDX_XDXDX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.17) THEN
        CALL EFT_SI_XDU_XDU_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.18) THEN
        CALL EFT_SI_XDXU_XDXU_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.19) THEN
        CALL EFT_SI_XDUX_XDUX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.20) THEN
        CALL EFT_SI_XDXUX_XDXUX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.21) THEN
        CALL EFT_SD_XDU_XDU_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.22) THEN
        CALL EFT_SD_XDXU_XDXU_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.23) THEN
        CALL EFT_SD_XDUX_XDUX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.24) THEN
        CALL EFT_SD_XDXUX_XDXUX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.25) THEN
        CALL EFT_SI_XDS_XDS_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.26) THEN
        CALL EFT_SI_XDXS_XDXS_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.27) THEN
        CALL EFT_SI_XDSX_XDSX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.28) THEN
        CALL EFT_SI_XDXSX_XDXSX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.29) THEN
        CALL EFT_SD_XDS_XDS_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.30) THEN
        CALL EFT_SD_XDXS_XDXS_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.31) THEN
        CALL EFT_SD_XDSX_XDSX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.32) THEN
        CALL EFT_SD_XDXSX_XDXSX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.33) THEN
        CALL EFT_SI_XDC_XDC_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.34) THEN
        CALL EFT_SI_XDXC_XDXC_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.35) THEN
        CALL EFT_SI_XDCX_XDCX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.36) THEN
        CALL EFT_SI_XDXCX_XDXCX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.37) THEN
        CALL EFT_SD_XDC_XDC_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.38) THEN
        CALL EFT_SD_XDXC_XDXC_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.39) THEN
        CALL EFT_SD_XDCX_XDCX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.40) THEN
        CALL EFT_SD_XDXCX_XDXCX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.41) THEN
        CALL EFT_SI_XDB_XDB_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.42) THEN
        CALL EFT_SI_XDXB_XDXB_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.43) THEN
        CALL EFT_SI_XDBX_XDBX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.44) THEN
        CALL EFT_SI_XDXBX_XDXBX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.45) THEN
        CALL EFT_SD_XDB_XDB_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.46) THEN
        CALL EFT_SD_XDXB_XDXB_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.47) THEN
        CALL EFT_SD_XDBX_XDBX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.48) THEN
        CALL EFT_SD_XDXBX_XDXBX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.49) THEN
        CALL EFT_SI_XDEM_XDEM_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.50) THEN
        CALL EFT_SI_XDXEM_XDXEM_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.51) THEN
        CALL EFT_SI_XDEP_XDEP_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.52) THEN
        CALL EFT_SI_XDXEP_XDXEP_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.53) THEN
        CALL EFT_SD_XDEM_XDEM_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.54) THEN
        CALL EFT_SD_XDXEM_XDXEM_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.55) THEN
        CALL EFT_SD_XDEP_XDEP_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.56) THEN
        CALL EFT_SD_XDXEP_XDXEP_SMATRIX(P_EXT, SMATRIX)

      ENDIF

      SMATRIX_DD_EFF = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD_TOT(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process for the effective + full lagrangian          
C            c
C     relevant for direct detection.                                  
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_TOT_DD --- generates series of if-then-else
C      statements to call appropriate smatrix
      IF (K.EQ.1) THEN
        CALL TOT_SI_XDT_XDT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.2) THEN
        CALL TOT_SI_XDXT_XDXT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.3) THEN
        CALL TOT_SI_XDTX_XDTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.4) THEN
        CALL TOT_SI_XDXTX_XDXTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.5) THEN
        CALL TOT_SD_XDT_XDT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.6) THEN
        CALL TOT_SD_XDXT_XDXT_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.7) THEN
        CALL TOT_SD_XDTX_XDTX_SMATRIX(P_EXT, SMATRIX)
      ELSEIF (K.EQ.8) THEN
        CALL TOT_SD_XDXTX_XDXTX_SMATRIX(P_EXT, SMATRIX)

      ENDIF

      SMATRIX_DD_TOT = SMATRIX
      RETURN
      END

