C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjM(-3,3)*ProjM(-2,1) +
C      Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjP(-3,3)*ProjP(-2,1)
C     
      SUBROUTINE FFFF10_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 VERTEX
      TMP3 = (F1(3)*F3(4)*(F2(5)*F4(6)-F2(6)*F4(5))+F1(4)*F3(3)*(-F2(5)
     $ *F4(6)+F2(6)*F4(5)))
      TMP4 = (F1(5)*F3(6)*(F2(3)*F4(4)-F2(4)*F4(3))+F1(6)*F3(5)*(-F2(3)
     $ *F4(4)+F2(4)*F4(3)))
      VERTEX = COUP*(-2D0)*(+CI*(TMP3+TMP4))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjM(-3,3)*ProjM(-2,1) +
C      Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjP(-3,3)*ProjP(-2,1)
C     
      SUBROUTINE FFFF10_9_0(F1, F2, F3, F4, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFFF10_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF9_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


