"""
===========================
Indirect Detection Analysis
===========================

Compute indirect detection signals and limits from dark matter annihilation.

Overview
========

Indirect detection looks for products of dark matter annihilation in astrophysical environment where the dark
matter is denser. For instance, typical benchmarks for gamma-ray searches are the dSphs or the Galactic Center.

Indirect Detection via the Higgs Portal
=======================================

In this example, we study the process χ χ → b b~ using the Scalar Higgs Portal model and we 
compute the resulting gamma-ray spectra relevant for indirect detection using MadDM v3.0.

First, import the model and define the dark matter candidate. We use the ScalarHiggsPortal_NLO_UFO model, where
the dark matter particle is labeled 'n1' in this model.

.. code-block:: text

    MadDM> import model ScalarHiggsPortal_NLO_UFO
    MadDM> define darkmatter n1

Then, we generate the indirect detection process. This defines the channel for which the gamma-ray spectra will be computed.
We then output the process to a folder named 'HiggsPortal_bbbar', and we launch the process.

.. code-block:: text

    MadDM> generate indirect_detection b b~
    MadDM> output HiggsPortal_bbbar
    MadDM> launch HiggsPortal_bbbar

We enable the computation of the gamma-ray flux spectrum by setting:

.. code-block:: text

    MadDM> set indirect = flux_source

You can set the minimum value of the gamma-ray flux (in cm^-2 s^-1 GeV^-1)
to be stored in the output. Fluxes below this threshold will be discarded.

.. code-block:: text

    MadDM> set save_indirect_cont 1e-3


To save the full energy spectra generated by Pythia 8, you can set:

.. code-block:: text

    MadDM> set save_output spectra

You can enable more precise numerical integration for higher accuracy.

.. code-block:: text

    MadDM> set precise


Next, choose how to compute the thermally averaged annihilation cross section ⟨σv⟩.
Here we use the 'madevent' method, which is general-purpose.

.. code-block:: text

    MadDM> set sigmav_method madevent

To specify how many events should be generated per phase-space point, do:

.. code-block:: text

    MadDM> set nevents 100000

Set the dark matter mass (in GeV) with:

.. code-block:: text

    MadDM> set MXd 100

and finally launch the process pressing Enter.


Exiting MadDM
=============

.. code-block:: text

    MadDM> quit
"""
