c------------------------------------------------------------------------------c
c This file contains the needed information about all the DM particles.
c------------------------------------------------------------------------------c

      MDM( 1 ) = ABS( MDL_MXD )
      DOF_DM( 1 ) = 2.0
      DM_SM_SCATTERING( 1 ) = .FALSE.
      DM_NAMES( 1 ) ='xd'
      DM_INDEX( 1 ) = 2
      DM_ANTINAMES( 1 ) = 'xd~'
      DM_ANTIINDEX( 1 ) = 3

c------------------------------------------------------------------------------c
